---
kind: pipeline
type: docker
name: Build

steps:
  - name: docker
    image: plugins/docker
    settings:
      insecure: false
      repo: registry.silvain.eu:5000/monsieurpatatebot
      registry: registry.silvain.eu:5000
      tags:
        - latest
